export const createFallbackPlanet = () => ({
  name: "",
  rotation_period: "",
  orbital_period: "",
  diameter: "",
  climate: "",
  gravity: "",
  terrain: "",
  surface_water: "",
  population: "",
  residents: [],
  films: [],
  url: "",
  created: "",
  edited: "",
});
